"""Initial migration

Revision ID: 7ed1d6fcce46
Revises: 
Create Date: 2024-09-17 13:39:26.717116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "7ed1d6fcce46"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('customers_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="customers_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_customers_phone", "customers", ["phone"], unique=True)
    op.create_index("ix_customers_name", "customers", ["name"], unique=False)
    op.create_index("ix_customers_id", "customers", ["id"], unique=False)
    op.create_index("ix_customers_code", "customers", ["code"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("item", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("customer_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name="orders_customer_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="orders_pkey"),
    )
    op.create_index("ix_orders_item", "orders", ["item"], unique=False)
    op.create_index("ix_orders_id", "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_orders_id", table_name="orders")
    op.drop_index("ix_orders_item", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_customers_code", table_name="customers")
    op.drop_index("ix_customers_id", table_name="customers")
    op.drop_index("ix_customers_name", table_name="customers")
    op.drop_index("ix_customers_phone", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
