apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orders-service
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orders-service
    spec:
      containers:
        - env:
            - name: AFRICASTALKING_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: AFRICASTALKING_API_KEY
                  name: orders-service-env
            - name: AFRICASTALKING_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: AFRICASTALKING_USERNAME
                  name: orders-service-env
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: orders-service-env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: orders-service-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: http://localhost:8080/realms/sso/protocol/openid-connect/auth
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_PUBLIC_KEY
                  name: orders-service-env
            - name: KEYCLOAK_REALM
              value: sso
            - name: KEYCLOAK_TOKEN_URL
              value: http://localhost:8080/realms/sso/protocol/openid-connect/token
            - name: OPENID_CONNECT_CLIENT_ID
              value: orders-service
            - name: OPENID_CONNECT_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: OPENID_CONNECT_CLIENT_SECRET
                  name: orders-service-env
            - name: OPENID_CONNECT_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENID_CONNECT_URL
                  name: orders-service-env
          image: orders-service
          name: orders-service
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
