apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orders-db
  name: orders-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orders-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orders-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: orders
            - name: POSTGRES_PASSWORD
              value: ordersdbpassword
            - name: POSTGRES_USER
              value: postgres
          image: postgres:16
          name: orders-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: orders-data
      restartPolicy: Always
      volumes:
        - name: orders-data
          persistentVolumeClaim:
            claimName: orders-data
